
trigger:
  branches:
    include:
      - main
      - releases/*
  paths:
    exclude:
      - README.md
      - LICENSE


pr:
  drafts: false
  branches:
    include:
      - main
      - release/*
  paths:
    exclude:
      - README.md
      - LICENSE


jobs:
  - job:
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macos-latest'
        windows:
          imageName: 'windows-latest'

    pool:
      vmImage: $(imageName)

    steps:

    - checkout: self
      persistCredentials: true
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: '12.17.0'
      displayName: 'Install Node.js'

    # @itwin/pcf build

    - script: |
        npm ci
      displayName: 'npm ci'
      workingDirectory: core

    - script: |
         npm run build
      displayName: 'npm run build'
      workingDirectory: core

    - script: |
        npm run test:unit
      displayName: 'npm run test:unit'
      workingDirectory: core

    - script: |
        npm run test:integration
      displayName: 'npm run test:integration'
      workingDirectory: core
      env:
        rate_limited: $(rate_limited)
        imjs_test_project_id: $(test_project_id)
        imjs_test_client_id: $(test_client_id)
        imjs_test_regular_user_name: $(test_user_name)
        imjs_test_regular_user_password: $(test_user_password)

    - script: |
        npm link
      displayName: 'npm link'
      workingDirectory: core

    # @itwin/pcf-cli build

    - script: |
        npm ci
      displayName: 'npm ci'
      workingDirectory: cli

    - script: |
        npm install -g .
      displayName: 'npm install -g .'
      workingDirectory: cli

    - script: |
        pcf init TestConnector TestClientId
      displayName: 'pcf init'
      workingDirectory: cli

    - script: |
        npm link @itwin/pcf
      displayName: 'npm link @itwin/pcf'
      workingDirectory: cli/output

    - script: |
        npm run build
      displayName: 'build generated connector'
      workingDirectory: cli/output

    # publish artifact

    - script: |
        npm pack
      displayName: 'Package @itwin/pcf for release'
      workingDirectory: core

    - script: |
        npm pack
      displayName: 'Package @itwin/pcf-cli for release'
      workingDirectory: cli

    - task: CopyFiles@2
      inputs:
        sourceFolder: core
        contents: '*.tgz'
        targetFolder: $(Build.ArtifactStagingDirectory)/packages
      displayName: 'Copy @itwin/pcf archives to artifacts staging directory'

    - task: CopyFiles@2
      inputs:
        sourceFolder: cli
        contents: '*.tgz'
        targetFolder: $(Build.ArtifactStagingDirectory)/packages
      displayName: 'Copy @itwin/pcf-cli archives to artifacts staging directory'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/packages'
        artifactName: packages
      displayName: 'Publish npm package artifacts'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Agent.OS'], 'Windows_NT'))

