
trigger:
  - none

jobs:

  - job:
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macos-latest'
        windows:
          imageName: 'windows-latest'

    pool:
      vmImage: $(imageName)

    steps:

    - checkout: self
      persistCredentials: true
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: '12.17.0'
      displayName: 'Install Node.js'

    # @itwin/pcf

    - script: |
        npm ci
      displayName: 'npm ci'
      workingDirectory: core

    - script: |
         npm run build
      displayName: 'npm run build'
      workingDirectory: core

    - script: |
        npm run test:unit
      displayName: 'npm run test:unit'
      workingDirectory: core

    - script: |
        npm run test:integration
      displayName: 'npm run test:integration'
      workingDirectory: core
      env:
        imjs_test_project_id: $(test_project_id)
        imjs_test_client_id: $(test_client_id)
        imjs_test_regular_user_name: $(test_user_name)
        imjs_test_regular_user_password: $(test_user_password)

    - script: |
        npm link
      displayName: 'npm link'
      workingDirectory: core

    # @itwin/pcf-cli

    - script: |
        npm ci
      displayName: 'npm ci'
      workingDirectory: cli

    - script: |
        npm install -g .
      displayName: 'npm install -g .'
      workingDirectory: cli

    - script: |
        pcf init TestConnector TestClientId
      displayName: 'pcf init'
      workingDirectory: cli

    - script: |
        npm link @itwin/pcf
      displayName: 'npm link @itwin/pcf'
      workingDirectory: cli/output

    - script: |
        npm run build
      displayName: 'build generated connector'
      workingDirectory: cli/output

