
# trigger:
#   - main
#   - release/*
#
# pr:
#   drafts: false
#   branches:
#     include:
#     - master
#     - release/*

trigger: none

jobs:
  - job:
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-lastest'
        mac:
          imageName: 'macos-latest'
        windows:
          imageName: 'vs2017-latest'
    
    pool:
      vmImage: $(imageName)

    steps:

    - checkout: self
      persistCredentials: true
      clean: true
    
    - script: # to cwd
      workingDirectory: core

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
      displayName: 'npm ci'

    - script: |
         npm run build
      displayName: 'npm run build'

    - script: |
        npm run test:unit
      displayName: 'npm run test:unit'

    - script: |
        npm run test:integration
      displayName: 'npm run test:integration'
    
    - script: |
        npm pack
      displayName: 'Package for release'

    - bash: | # Grab the package version
        v=`node -p "const p = require('./package.json'); p.version;"`
        echo "##vso[task.setvariable variable=packageVersion]$v"
